name: create-redocly

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths:
      - utm.yaml # only trigger off changes to this file
      - .github/workflows/create-redocly.yaml

jobs:

  generate_html:
    runs-on: ubuntu-latest
    name: Generate static HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # use the public name of the action
      - name: redoc-cli
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle utm.yaml -o docs/utm.html'

      - name: check result
        run: |
          ls -al
          test -f docs/utm.html || (echo "Missing utm.html from previous step." && exit 1)
      
  #    - name: Commit changes
  #      uses: EndBug/add-and-commit@v7
  #      with:
  #        committer_name: create-redocly-action
  #        message: 'Automated commit via create-redocly'
  #        branch: gh-pages
  #        add: 'utm.html --force'
  #        push: true
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

