name: create-redocly

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:

  generate_html:
    runs-on: ubuntu-latest
    name: Generate static HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # use the public name of the action
      - name: redoc-cli
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle utm.yaml -o utm.html'

      - name: check result
        run: |
          ls -al
          test -f utm.html || (echo "Missing utm.html from previous step." && exit 1)
      
      #- name: Commit changes
        #uses: EndBug/add-and-commit@v7
        #with:
         # committer_name: create-redocly-action
         # message: 'Automated commit via create-redocly'
         # branch: gh-pages
         # add: 'utm.html --force'
         # push: true
      - name: Commit Changes
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch gh-pages
          git add utm.html
          git commit -m "Commit via GH action"
          git push
