name: create-redocly

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths:  # only trigger off changes to these files
      - utm.yaml 
      - .github/workflows/create-redocly.yaml

jobs:

  generate_html:
    runs-on: ubuntu-latest
    name: Generate static HTML
    steps:
      # Checkout the repo into the running Docker
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the HTML using an Action from the Marketplace
      - name: redoc-cli
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle utm.yaml -o docs/utm.html'

      # Simple check that the file was generated
      - name: check result
        run: |
          ls -al
          test -f docs/utm.html || (echo "Missing utm.html from previous step." && exit 1)

      # Get the file into the right branch/location for serving via GH Pages
      # Again using an Action from Marketplace to accomplish
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

