name: validate-openapi

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths:  # only trigger off changes to these files
      - utm.yaml 
      - .github/workflows/validate-openapi.yaml

jobs:

  validate_openapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Swagger Validator
      uses: mbowman100/swagger-validator-action@master
      with:
        files: utm.yaml
