name: validate-openapi

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths:  # only trigger off changes to these files
      - utm.yaml 
      - .github/workflows/validate-openapi.yaml

jobs:

  validate_openapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Get list of files
      run:  |
        # Using github env (newline separated file list)
        echo 'FILE_LIST<<EOF' >> $GITHUB_ENV
        find lib -type f -iname "utm.yaml" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

        # Using step output (space separated file list)
        FILES="$(find lib -type f -iname "utm.yaml")"
        echo "::set-output name=file_list::$FILES"
        
    - name: Swagger Validator
      uses: mbowman100/swagger-validator-action@master
      if: env.FILE_COUNT != '0' # Comment out if you want it to fail if no files found
      with:
        files: ${{ env.FILE_LIST }}
        # files: ${{ steps.getfiles.outputs.file_list }} # For if you're using output
